---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "brew.wang"
subtitle: "Gray"
logo: "favicon.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: 'power by <a href="http://grayblog.cn/">Gray</a>, // Fork me on <a href="https://github.com/graylogo"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example)
# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#4a4a4a"
    highlight-secondary: "#7a7a7a"
    highlight-hover: "#b5b5b5"
    background: "#dbdbdb"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "green"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "header-color" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "å…³äºæˆ‘ !"
  icon: "fa fa-grin"
  content: "ä¸‹é¢æ˜¯æˆ‘çš„ä¸ªäººé¡¹ç›®. <br /> å»æˆ‘çš„åšå®¢æŸ¥çœ‹æ›´å¤š <a href='https://github.com/graylogo/homer' target='_black'>grayblog/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/graylogo"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "#"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "ä¸ªäººé¡¹ç›®"
    icon: "fas fa-code"
    items:
      - name: "æˆ‘çš„åšå®¢"
        logo: "/favicon.png"
        subtitle: "ç‚¹å‡»è·³è½¬åšå®¢ä¸»é¡µ"
        tag: "blog"
        url: "http://grayblog.cn/"
        target: "_blank" # optional html a tag target attribute
      - name: "å­¦ä¹ ç¬”è®°"
        logo: "assets/tools/book.jpg"
        subtitle: "æ¯å¤©è¿›æ­¥ä¸€ç‚¹ç‚¹ğŸ‘»"
        tag: "GitBook"
        url: "#"
      - name: "ç¨‹åºå‘˜äº¤æµç¤¾åŒº"
        logo: "assets/tools/chat.jpg"
        subtitle: "ä¸€ä¸ªç¨‹åºå‘˜çš„äº¤æµç¤¾åŒº"
        tag: "app"
        url: "#"
      - name: "æµ‹è¯•é¡¹ç›®"
        logo: "assets/tools/node.jpg"
        subtitle: "NodeJs+Vue+MongoDB"
        tag: "app2"
        url: "#"
      - name: "æ›´å¤šé¡¹ç›®å­¦ä¹ ä¸­ã€‚ã€‚ã€‚"
        logo: "assets/tools/more.jpg"
        subtitle: "æ•¬è¯·æœŸå¾…ï¼"
        tag: "others"
        url: "#"